class_name KeyUtils extends Node


static func keycode_to_char(keycode: Key) -> String:
	var out = OS.get_keycode_string(keycode)
	if len(out) == 1: return out
	
	match keycode:
		KEY_AMPERSAND: return "&"
		KEY_ASCIICIRCUM: return "^"
		KEY_ASCIITILDE: return "~"
		KEY_ASTERISK: return "*"
		KEY_APOSTROPHE: return "\'"
		KEY_AT: return "@"
		KEY_BACKSPACE: return "b"
		KEY_BACKSLASH: return "\\"
		KEY_BRACELEFT: return "{"
		KEY_BRACERIGHT: return "}"
		KEY_BRACKETLEFT: return "["
		KEY_BRACKETRIGHT: return "]"
		KEY_COLON: return ":"
		KEY_COMMA: return ","
		KEY_DOLLAR: return "$"
		KEY_DELETE: return "d"
		KEY_DOWN: return "↓"
		KEY_END: return "e"
		KEY_ENTER: return "↲"
		KEY_EQUAL: return "="
		KEY_EXCLAM: return "!"
		KEY_F1: return "1"
		KEY_F2: return "2"
		KEY_F3: return "3"
		KEY_F4: return "4"
		KEY_F5: return "5"
		KEY_F6: return "6"
		KEY_F7: return "7"
		KEY_F8: return "8"
		KEY_F9: return "9"
		KEY_F10: return "10"
		KEY_F11: return "11"
		KEY_F12: return "12"
		KEY_GREATER: return ">"
		KEY_HOME: return "h"
		KEY_INSERT: return "i"
		KEY_KP_0: return "0"
		KEY_KP_1: return "1"
		KEY_KP_2: return "2"
		KEY_KP_3: return "3"
		KEY_KP_4: return "4"
		KEY_KP_5: return "5"
		KEY_KP_6: return "6"
		KEY_KP_7: return "7"
		KEY_KP_8: return "8"
		KEY_KP_9: return "1"
		KEY_KP_ADD: return "+"
		KEY_KP_DIVIDE: return "/"
		KEY_KP_ENTER: return "↲"
		KEY_KP_MULTIPLY: return "*"
		KEY_KP_PERIOD: return "."
		KEY_KP_SUBTRACT: return "-"
		KEY_LEFT: return "←"
		KEY_LESS: return "<"
		KEY_MINUS: return "-"
		KEY_NUMBERSIGN: return "#"
		KEY_PAGEDOWN: return "↡"
		KEY_PAGEUP: return "↟"
		KEY_PARENLEFT: return "("
		KEY_PARENRIGHT: return ")"
		KEY_PERCENT: return "%"
		KEY_PERIOD: return "."
		KEY_PLUS: return "+"
		KEY_QUESTION: return "?"
		KEY_QUOTEDBL: return "\""
		KEY_QUOTELEFT: return "`"
		KEY_RIGHT: return "→"
		KEY_SECTION: return "§"
		KEY_SEMICOLON: return ";"
		KEY_SLASH: return "/"
		KEY_SPACE: return "_"
		KEY_UNDERSCORE: return "_"
		KEY_UP: return "↑"
		KEY_YEN: return "¥"
		KEY_JIS_EISU: return "英"
		KEY_JIS_KANA: return "か"
	return out.left(1)
